server:
  port: 8000
spring:
  dubbo: 
    application:
      name: demo-provider1
    base-package: com.provider.service  # dubbo服务发布者所在的包
    registry:
      address:  zookeeper://127.0.0.1:2181    # zookeeper注册中心的地址
    protocol:
      name: dubbo
      serialization: hessian2
    provider:
      retries: 0                           # 服务调用重试次数，服务发布者不给重试，让服务调用者自己